import {rules,assess,batch,parseCSV,csvCell,restore} from './core.mjs';
const $=s=>document.querySelector(s),key='paymentguard.browser.v1';
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const usd=c=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(c/100);
let state={payments:[],cases:{},revision:0},saved=null,page='overview',offset=0,pending=[],caseRef=null,blocked=false;
function notify(message){$('#notice').hidden=false;$('#notice').textContent=message;}
try{saved=localStorage.getItem(key);if(saved){state=restore(JSON.parse(saved));}}catch{blocked=true;notify('Saved data could not be read. Changes are disabled to protect it. Export your browser backup from Data & reports before clearing this workspace.');}
function save(next){if(blocked)throw Error('Storage is unavailable. Export your backup before clearing this workspace.');if(localStorage.getItem(key)!==saved)throw Error('This workspace changed in another tab. Reload before saving.');const str=JSON.stringify({...next,revision:Date.now()});try{localStorage.setItem(key,str);}catch{throw Error('Browser storage is full or unavailable. Export a backup; no changes were saved.');}saved=str;state=JSON.parse(str);}
window.addEventListener('storage',e=>{if(e.key===key){blocked=true;notify('This workspace changed in another tab. Reload this page before continuing.');}});
const empty=(title,text)=>`<div class="empty"><h2>${title}</h2><p>${text}</p><button class="primary" data-add>Add your first payment</button></div>`;
function summary(){const results=state.payments.map(assess);return {volume:state.payments.reduce((a,p)=>a+p.cents,0),signals:results.filter(r=>r.signals.length).length,unknown:results.filter(r=>r.score===null).length};}
function table(rows,actions=true){return `<div class="table-wrap"><table><thead><tr><th>Reference</th><th>Customer</th><th>Amount</th><th>Status</th><th>Risk points</th>${actions?'<th>Review</th>':''}</tr></thead><tbody>${rows.map(p=>{const r=assess(p);return `<tr><td>${esc(p.external_id)}<br><small>${esc(new Date(p.occurred_at).toLocaleDateString())} · ${p.direction}</small></td><td>${esc(p.customer_ref)}</td><td>${usd(p.cents)}</td><td><span class="badge">${p.status}</span></td><td><span class="badge ${r.signals.length?'flag':''}">${r.score===null?'Not assessed':r.score+' / 100'}</span><br><small>${r.evaluated}/12 rules evaluated</small></td>${actions?`<td><button data-case="${esc(p.external_id)}">Investigate</button></td>`:''}</tr>`;}).join('')}</tbody></table></div>`;}
function overview(){const s=summary();return `<div class="metrics">${[['Payment volume',usd(s.volume)],['Payments',state.payments.length],['With risk signals',s.signals],['Open investigations',Object.values(state.cases).filter(c=>c.status!=='closed').length]].map(([l,v])=>`<div class="metric"><p>${l}</p><strong>${v}</strong></div>`).join('')}</div>${!state.payments.length?`<section class="panel">${empty('Your workspace starts here.','Add your own payment events to see activity, risk signals, and investigation history. Nothing is preloaded.')}</section>`:`<div class="grid"><section class="panel"><h2>Payment activity</h2><p class="muted">Submitted event amounts by UTC date · USD</p>${chart()}</section><section class="panel"><h2>Evidence coverage</h2><p class="muted">${s.unknown} payments have no supplied risk context.</p><strong>${state.payments.length-s.unknown} / ${state.payments.length} payments assessed</strong><p class="muted">No triggered rule does not mean a payment is safe. Missing evidence remains unknown.</p><button data-page="controls">View risk controls</button></section></div><section class="panel" style="margin-top:20px"><h2>Latest payments</h2>${table([...state.payments].reverse().slice(0,5))}</section>`}`;}
function chart(){const totals={};for(const p of state.payments){const d=p.occurred_at.slice(0,10);totals[d]=(totals[d]||0)+p.cents;}const entries=Object.entries(totals).sort().slice(-7),max=Math.max(...entries.map(e=>e[1]));return entries.map(([d,v])=>`<div class="bar-row"><span>${d.slice(5)}</span><div class="bar-track"><div class="bar" style="width:${v/max*100}%"></div></div><span>${usd(v)}</span></div>`).join('')+'<small>Most recent 7 dates with activity</small>';}
function payments(){return `<section class="panel"><h2>Payment records</h2><div class="filters"><input id="search" aria-label="Search payments" placeholder="Search payment or customer reference"><select id="status-filter" aria-label="Filter by status"><option value="">All statuses</option>${['pending','settled','blocked','returned'].map(s=>`<option>${s}</option>`).join('')}</select></div><div id="payment-results"></div></section>`;}
function renderPayments(){const term=$('#search').value.toLowerCase(),status=$('#status-filter').value;const rows=[...state.payments].reverse().filter(p=>(p.external_id.toLowerCase().includes(term)||p.customer_ref.toLowerCase().includes(term))&&(!status||p.status===status));offset=Math.min(offset,Math.max(0,Math.floor((rows.length-1)/25)*25));$('#payment-results').innerHTML=rows.length?table(rows.slice(offset,offset+25))+`<div class="pager"><button id="prev" ${offset===0?'disabled':''}>Previous</button><small>${offset+1}–${Math.min(offset+25,rows.length)} of ${rows.length}</small><button id="next" ${offset+25>=rows.length?'disabled':''}>Next</button></div>`:'<p class="muted">No matching payments.</p>';$('#prev')?.addEventListener('click',()=>{offset-=25;renderPayments();});$('#next')?.addEventListener('click',()=>{offset+=25;renderPayments();});}
function investigations(){const cases=Object.entries(state.cases);return `<section class="panel"><h2>Investigation history</h2><p class="muted">Notes and statuses are saved in this browser. This is an editable working record, not a tamper-proof audit log.</p>${cases.length?cases.map(([id,c])=>`<article class="control"><h3>${esc(id)} <span class="badge">${esc(c.status)}</span></h3><p>${esc(c.note||'No notes yet.')}</p><small>Updated ${esc(new Date(c.updated).toLocaleString())}</small><div class="actions"><button data-case="${esc(id)}">Review case</button></div><details><summary>Saved history</summary>${(Array.isArray(c.history)?c.history:[]).slice().reverse().map(h=>`<p>${esc(new Date(h.updated).toLocaleString())} · ${esc(h.status)}<br>${esc(h.note)}</p>`).join('')}</details></article>`).join(''):'<div class="empty"><h2>No investigations yet.</h2><p>Open a payment and select Investigate to record your review.</p><button data-page="payments">View payments</button></div>'}</section>`;}
function controls(){return `<section class="panel"><h2>Transparent risk controls</h2><p class="muted">Only rules with all required evidence are evaluated. Points are capped at 100. These checks support review; they do not verify fraud or execute payment decisions.</p><div class="control-list">${rules.map(([name,weight,fields,fn,desc],i)=>`<article class="control"><span class="eyebrow">R${String(i+1).padStart(2,'0')} · ${weight} POINTS</span><h3>${name}</h3><p>${desc}</p><code>${fields.join(', ')}</code></article>`).join('')}</div></section>`;}
function data(){return `<div class="grid"><section class="panel"><h2>Import payment records</h2><p class="muted">CSV · up to 5,000 rows / 2 MB per import. Duplicate references reject the entire batch. This workspace supports 10,000 payments.</p><button id="template">Download empty template</button><label style="margin-top:18px">Choose CSV<input id="csv-file" type="file" accept=".csv,text/csv"></label><p class="error" id="import-error" role="alert"></p><div id="import-preview"></div></section><section class="panel"><h2>Your data, in your browser</h2><p class="muted">There is no password, cloud backup, or device sync. Anyone with access to this browser profile can view these records. Clearing site data removes them.</p><div class="actions"><button id="export-csv">Export payments CSV</button><button id="backup">Download full backup</button></div><p class="muted">The JSON backup includes investigation notes and history. Keep it somewhere private.</p><label>Restore full JSON backup<input id="restore" type="file" accept=".json,application/json"></label><p class="error" id="restore-error" role="alert"></p><div class="actions"><button class="danger" id="clear">Clear this browser workspace</button></div></section></div>`;}
function render(){const names={overview:'Overview',payments:'Payments',investigations:'Investigations',controls:'Risk controls',data:'Data & reports'};$('#title').textContent=names[page];document.querySelectorAll('nav button').forEach(b=>b.setAttribute('aria-current',b.dataset.page===page?'page':'false'));$('#content').innerHTML=({overview,payments,investigations,controls,data}[page])();if(page==='payments'){renderPayments();$('#search').oninput=()=>{offset=0;renderPayments();};$('#status-filter').onchange=()=>{offset=0;renderPayments();};}if(page==='data')bindData();}
function add(){const form=$('#payment-form');form.reset();const now=new Date();form.elements.time.value=new Date(now-now.getTimezoneOffset()*60000).toISOString().slice(0,16);$('#form-error').textContent='';$('#payment-dialog').showModal();}
document.addEventListener('click',e=>{const btn=e.target.closest('button');if(!btn)return;if(btn.dataset.page){page=btn.dataset.page;pending=[];render();}if(btn.hasAttribute('data-add')||btn.id==='add')add();if(btn.classList.contains('close'))btn.closest('dialog').close();if(btn.dataset.case)openCase(btn.dataset.case);});
$('#payment-form').onsubmit=e=>{e.preventDefault();try{const f=Object.fromEntries(new FormData(e.target));let evidence;try{evidence=JSON.parse(f.evidence||'{}');}catch{throw Error('Additional evidence must be valid JSON.');}if(!evidence||typeof evidence!=='object'||Array.isArray(evidence))throw Error('Evidence must be a JSON object.');for(const k of ['account_age','tx_count_1h','failed_logins','customer_avg_amount'])if(f[k]!=='')evidence[k]=Number(f[k]);const incoming=batch([{...f,occurred_at:new Date(f.time).toISOString(),evidence}],state.payments);save({...state,payments:[...state.payments,...incoming]});$('#payment-dialog').close();render();notify('Payment saved. Your totals are up to date.');}catch(err){$('#form-error').textContent=err.message;}};
function openCase(id){const p=state.payments.find(p=>p.external_id===id);if(!p)return;caseRef=id;const c=state.cases[id],r=assess(p);$('#case-reference').textContent=`${id} · ${usd(p.cents)} · ${r.signals.map(s=>s.name).join('; ')||'No triggered signals'} · ${r.evaluated}/12 rules evaluated`;$('#case-form').elements.status.value=c?.status||'open';$('#case-form').elements.note.value=c?.note||'';$('#case-error').textContent='';$('#case-dialog').showModal();}
$('#case-form').onsubmit=e=>{e.preventDefault();try{const f=Object.fromEntries(new FormData(e.target));if(!f.note.trim())throw Error('Add a note explaining your review.');const item={status:f.status,note:f.note.trim(),updated:new Date().toISOString()};const history=[...(state.cases[caseRef]?.history||[]),item];save({...state,cases:{...state.cases,[caseRef]:{...item,history}}});$('#case-dialog').close();render();notify('Investigation saved.');}catch(err){$('#case-error').textContent=err.message;}};
function download(text,name,type){const url=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
const headers=['external_id','customer_ref','occurred_at','amount','direction','status','currency','evidence'];
function bindData(){
 $('#template').onclick=()=>download(headers.join(',')+'\n','paymentguard-template.csv','text/csv');
 $('#export-csv').onclick=()=>download([headers.join(','),...state.payments.map(p=>[p.external_id,p.customer_ref,p.occurred_at,(p.cents/100).toFixed(2),p.direction,p.status,'USD',JSON.stringify(p.evidence)].map(csvCell).join(','))].join('\r\n'),'paymentguard-payments.csv','text/csv');
 $('#backup').onclick=()=>download(saved||JSON.stringify(state,null,2),'paymentguard-backup.json','application/json');
 $('#clear').onclick=()=>{if(!confirm('Clear all payments and investigations in this browser? Download a backup first. This cannot be undone without a backup.'))return;try{localStorage.removeItem(key);saved=null;state={payments:[],cases:{},revision:0};blocked=false;render();notify('Browser workspace cleared. All totals are zero.');}catch{notify('Browser storage cannot be cleared. Check your browser settings.');}};
 $('#csv-file').onchange=async e=>{pending=[];$('#import-preview').innerHTML='';$('#import-error').textContent='';const f=e.target.files[0];if(!f)return;try{if(f.size>2*1024*1024)throw Error('CSV must be 2 MB or smaller.');const records=parseCSV(await f.text());pending=batch(records,state.payments);$('#import-preview').innerHTML=`<h3>${pending.length} valid payments · ${usd(pending.reduce((a,p)=>a+p.cents,0))}</h3><p class="muted">Preview of the first 5 records. Nothing is saved until you confirm.</p>${table(pending.slice(0,5),false)}<div class="actions"><button class="primary" id="confirm-import">Import ${pending.length} payments</button></div>`;$('#confirm-import').onclick=()=>{try{if(!pending.length)return;save({...state,payments:[...state.payments,...pending]});const count=pending.length;pending=[];render();notify(`Imported ${count} payments.`);}catch(err){$('#import-error').textContent=err.message;}};}catch(err){$('#import-error').textContent=err.message;}};
 $('#restore').onchange=async e=>{const f=e.target.files[0];if(!f)return;try{if(f.size>20*1024*1024)throw Error('Backup must be 20 MB or smaller.');const {payments,cases}=restore(JSON.parse(await f.text()));if(!confirm(`Replace this browser workspace with ${payments.length} payments and ${Object.keys(cases).length} investigations from the backup?`))return;save({payments,cases});render();notify('Backup restored.');}catch(err){$('#restore-error').textContent=err.message;}};
}
render();
